//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table()
        {
            this.Wyplata = new HashSet<Wyplata>();
        }
    
        public int IdUzytkownika { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<System.DateTime> Data_Urodzenia { get; set; }
        public string Pesel { get; set; }
        public string Dzial { get; set; }
        public Nullable<double> WyplataBrutto { get; set; }
        public Nullable<int> Uprawnienia { get; set; }
        public string Haslo { get; set; }
        public Nullable<double> benefit { get; set; }
        public Nullable<int> potwierdzenie { get; set; }
        public string login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wyplata> Wyplata { get; set; }
    }
}
